(function() {var implementors = {};
implementors["nonsmallnum"] = ["impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/arith/trait.Mul.html\" title=\"trait core::ops::arith::Mul\">Mul</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u32.html\">u32</a>&gt; for &amp;'a <a class=\"struct\" href=\"nonsmallnum/struct.NonSmallInt.html\" title=\"struct nonsmallnum::NonSmallInt\">NonSmallInt</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/arith/trait.Mul.html\" title=\"trait core::ops::arith::Mul\">Mul</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u32.html\">u32</a>&gt; for <a class=\"struct\" href=\"nonsmallnum/struct.NonSmallInt.html\" title=\"struct nonsmallnum::NonSmallInt\">NonSmallInt</a>","impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/arith/trait.Mul.html\" title=\"trait core::ops::arith::Mul\">Mul</a> for &amp;'a <a class=\"struct\" href=\"nonsmallnum/struct.NonSmallInt.html\" title=\"struct nonsmallnum::NonSmallInt\">NonSmallInt</a>","impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/arith/trait.Mul.html\" title=\"trait core::ops::arith::Mul\">Mul</a>&lt;<a class=\"struct\" href=\"nonsmallnum/struct.NonSmallInt.html\" title=\"struct nonsmallnum::NonSmallInt\">NonSmallInt</a>&gt; for &amp;'a <a class=\"struct\" href=\"nonsmallnum/struct.NonSmallInt.html\" title=\"struct nonsmallnum::NonSmallInt\">NonSmallInt</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/arith/trait.Mul.html\" title=\"trait core::ops::arith::Mul\">Mul</a> for <a class=\"struct\" href=\"nonsmallnum/struct.NonSmallInt.html\" title=\"struct nonsmallnum::NonSmallInt\">NonSmallInt</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
